- hosts: '{{ host }}'
  become: yes
  tasks:

    - name: install mosquitto packages
      apt: name={{ item }}  update_cache=yes state=latest
      with_items:
        - mosquitto
        - mosquitto-clients
        - libmosquitto-dev
        - libmosquitto1

